const HIGHLIGHTSBCN_AUTH_API_URL = process.env.REACT_APP_HIGHLIGHTSBCN_AUTH_API_URL;
const HIGHLIGHTSBCN_AUTH_API_PORT = process.env.REACT_APP_HIGHLIGHTSBCN_AUTH_API_PORT || 443;
const HIGHLIGHTSBCN_AUTH_API_BASE_PATH = process.env.REACT_APP_HIGHLIGHTSBCN_AUTH_API_BASE_PATH || '/';

const authApi = {
  BASE_PATH: HIGHLIGHTSBCN_AUTH_API_BASE_PATH,
  BASE_URL: `${HIGHLIGHTSBCN_AUTH_API_URL}:${HIGHLIGHTSBCN_AUTH_API_PORT}${HIGHLIGHTSBCN_AUTH_API_BASE_PATH}`,
};

export default authApi;
